name: Codecov
env:
    DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate '.xcodeproj'
      run: swift package generate-xcodeproj
    - name: Run Tests using 'xcodebuild'
      run: xcodebuild test -enableCodeCoverage YES -scheme TGAImage-Package
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1.0.13
