name: SwiftLint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
    - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
